version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/repo
    stages:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm ci

      # because we use "npm ci" to install NPM dependencies
      # we cache "~/.npm" folder
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run: npm run style
      - run: npm run lint

      - run: npm run build:prod
      - run: npm run test:coverage -- --watch=false
      - run: npm run e2e

      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/local-weather-app
      - store_artifacts:
          path: dist.tar.gz
workflows:
  build-and-test:
    jobs:
      - build
